force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>A specific training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>The date and time that the training concluded</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Number_of_Participants__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Participants__c</fullName>
    <inlineHelpText>The number of people who participated in Training.</inlineHelpText>
    <label>Number of Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Restaurant__c.field-meta.xml
<CustomField>
    <fullName>Restaurant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If training takes too long, the restaurant will be included</inlineHelpText>
    <label>Restaurant</label>
    <referenceTo>Restaurant__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>The date and time that the training began</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Indicates whether a training is planned, happening now, or has concluded</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Trainer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The trainer that will perform the training.</inlineHelpText>
    <label>Trainer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Training_Course__c.field-meta.xml
<CustomField>
    <fullName>Training_Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The course that was delivered in the training</inlineHelpText>
    <label>Training Course</label>
    <referenceTo>Training_Course__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Training_Length_Days__c.field-meta.xml
<CustomField>
    <fullName>Training_Length_Days__c</fullName>
    <formula>DATEVALUE(End_Date__c) - DATEVALUE(Start_Date__c)</formula>
    <inlineHelpText>The duration of the training in terms of days</inlineHelpText>
    <label>Training Length (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TrainingRestService.cls
@RestResource(UrlMapping='/Trainings/*')
global with sharing class TrainingRestService {

    @HttpGet
    global static void getTraining() {
        RestResponse res = RestContext.response;
        RestRequest req = RestContext.request;
        System.debug('get request: '+ req);
        Map<String, String> parameters = req.params;
        Id salesforceId = parameters.get('salesforceId');

        if(salesforceId == null){
            res.statusCode = 400;
            res.responseBody = Blob.valueOf('{"error": "salesforceId parameter is missing"}');
            return;
        } 

        Training__c training = [SELECT Id, Training_Length_Days__c, Status__c, Trainer_Contact__r.Name,
                                            Start_Date__c, End_Date__c, Number_of_Participants__c
                                            FROM Training__c
                                            WHERE Id = :salesforceId];
        res.responseBody = Blob.valueOf(JSON.serialize(training));
        res.statusCode = 200;
    }

    @HttpPost
    global static void insertTraining() {
        RestResponse res = RestContext.response;
        try {
            RestRequest req = RestContext.request;
            System.debug('insert request: '+ req);
            Map<String, String> parameters = req.params;

            String trainingName = parameters.get('trainingName');
            Date startDate = Date.valueOf(parameters.get('startDate'));
            Date endDate = Date.valueOf(parameters.get('endDate'));
            Id trainerId = parameters.get('trainerId');
            Id restaurantId = parameters.get('restaurantId');
            Id courseId = parameters.get('courseId');

            Training__c newTraining = new Training__c(
                Name = trainingName,
                Start_Date__c = startDate,
                End_Date__c = endDate,
                Trainer_Contact__c = trainerId,
                Restaurant__c = restaurantId,
                Training_Course__c = courseId
            );
            
            insert newTraining;
            res.responseBody = Blob.valueOf(JSON.serialize(newTraining));
            res.statusCode = 201; // Created
        } catch (Exception e) {
            res.statusCode = 500; // Internal Server Error
            res.responseBody = Blob.valueOf('{"error": "' + e.getMessage() + '"}');
        }
    }
}