force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>A specific training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>The date and time that the training concluded</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Indicates whether a training is planned, happening now, or has concluded</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Trainer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The trainer that will perform the training.</inlineHelpText>
    <label>Trainer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RenderStudentCertificatePDF.cls
public with sharing class RenderStudentCertificatePDF {
    public RenderStudentCertificatePDF() {

    }
    public void generateStudentCertificate(Id trainingId){
        List<contentVersion> pdfs = new List<contentVersion>();

        List<Participant__c> participants = [SELECT Id,Training__c,Status__c, Training__r.Name,Contact_Name__r.Name, Training__r.End_Date__c, Training__r.Trainer_Contact__r.Name
        FROM Participant__c
        WHERE Training__c =:trainingId and Status__c ='Participated'];

        for(Participant__c participant : participants){
            contentVersion newFile = renderPdf(participant.Id);
            pdfs.add(newFile);
        }

        insert pdfs;

    

    }
    public contentVersion renderPDF(Id participantId) {
        PageReference certificatePage = Page.StudentCertificate;
        certificatePage.getParameters().put('id', participantId);
        Blob pdfBlob = certificatePage.getContent();
        ContentVersion contentVersion = new ContentVersion();
        contentVersion.ContentLocation = 'S';
        contentVersion.PathOnClient = 'StudentCertificateDemo.pdf';
        contentVersion.Title = 'Student Certificate';
        contentVersion.VersionData = pdfBlob;
        contentVersion.FirstPublishLocationId = participantId;
        return contentVersion;

    }
}