force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>A specific training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>The date and time that the training concluded</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Number_of_Participants__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Participants__c</fullName>
    <inlineHelpText>The number of people who participated in Training.</inlineHelpText>
    <label>Number of Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Restaurant__c.field-meta.xml
<CustomField>
    <fullName>Restaurant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If training takes too long, the restaurant will be included</inlineHelpText>
    <label>Restaurant</label>
    <referenceTo>Restaurant__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>The date and time that the training began</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Indicates whether a training is planned, happening now, or has concluded</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Trainer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The trainer that will perform the training.</inlineHelpText>
    <label>Trainer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Training_Course__c.field-meta.xml
<CustomField>
    <fullName>Training_Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The course that was delivered in the training</inlineHelpText>
    <label>Training Course</label>
    <referenceTo>Training_Course__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ERPparticipantCalloutTest.cls
@isTest
public with sharing class ERPparticipantCalloutTest {
    @isTest
    public static void getERPidTest() {

        Restaurant__c restaurant = new Restaurant__c(
            Name = 'Test Restaurant',
            AverageMealCost__c = 0,
            CommissionRate__c = 10
        );
        Insert restaurant;

        Training_Course__c trainingCourse = new Training_Course__c(Name = 'Test Training Course');

		Insert trainingCourse;

        Contact trainerContact = new Contact(
            FirstName = 'John',
            LastName = 'Doe', 
            Email ='jdoe@test.net');
        Insert trainerContact;

        Training__c training = new Training__c(
            Name = 'Test Training',
            Restaurant__c = restaurant.id,
			Start_Date__c = Date.Today(),
			End_Date__c = Date.Today().addDays(2),
            Training_Course__c = trainingCourse.id,
			Trainer_Contact__c = trainerContact.id,
            Number_of_Participants__c = 0,
            Maximum_Participant_Capacity__c = 3
        );

        Insert training;

        Contact con = new Contact(FirstName = 'success', LastName = 'Carney', Email = 'dtcarney08@gmail.com');

        insert con;

        Participant__c participant = new Participant__c(Training__c = training.id, Contact_Name__c = con.id);

        Insert participant;

        List<Id> participantIds = new List<ID>();
        participantIds.add(participant.id);


        Test.setMock(HttpCalloutMock.class, new MockERPResponseGenerator());
        RegistrationConfirmationQueueable.bypassPaymentLinkCallout = TRUE;
        Test.startTest();
        ERPparticipantCallout.getERPid(participantIds);
        Test.stopTest();

        Participant__c updatedParticipant = [SELECT Id, erpId__c FROM Participant__c WHERE Id =: participant.id LIMIT 1];
        System.debug('updatedParticipant: '+ updatedParticipant);
        Assert.areEqual('9174', updatedParticipant.erpId__c);

    }

    @isTest
    public static void createParticipantinERPTest() {

        Restaurant__c restaurant = new Restaurant__c(
            Name = 'Test Restaurant',
            AverageMealCost__c = 0,
            CommissionRate__c = 10
        );
        Insert restaurant;

        Training_Course__c trainingCourse = new Training_Course__c(Name = 'Test Training Course');

		Insert trainingCourse;

        Contact trainerContact = new Contact(
            FirstName = 'John',
            LastName = 'Doe', 
            Email ='jdoe@test.net');
        Insert trainerContact;

        Training__c training = new Training__c(
            Name = 'Test Training',
            Restaurant__c = restaurant.id,
			Start_Date__c = Date.Today(),
			End_Date__c = Date.Today().addDays(2),
            Training_Course__c = trainingCourse.id,
			Trainer_Contact__c = trainerContact.id,
            Number_of_Participants__c = 0,
            Maximum_Participant_Capacity__c = 3
        );

        Insert training;

        Contact con = new Contact(FirstName = 'success', LastName = 'Carney', Email = 'dtcarney08@gmail.com');

        insert con;

        Participant__c participant = new Participant__c(Training__c = training.id, Contact_Name__c = con.id);

        Insert participant;
        participant = [
            SELECT Id, Contact_Name__r.Email,Contact_Name__r.Name, Training__r.Name, Status__c, ErpId__c
            FROM Participant__c 
            WHERE Id =: participant.Id
        ];


        Test.setMock(HttpCalloutMock.class, new MockERPResponseGenerator());
        RegistrationConfirmationQueueable.bypassPaymentLinkCallout = TRUE;
        Test.startTest();
        participant = ERPparticipantCallout.createParticipantinERP(participant);
        System.debug('participant debug after callout: ' + participant);
        update participant;
        Test.stopTest();

        Participant__c updatedParticipant = [SELECT Id, erpId__c FROM Participant__c WHERE Id =: participant.id LIMIT 1];
        System.debug('updatedParticipant: '+ updatedParticipant);
        Assert.areEqual('9174', updatedParticipant.erpId__c);

    }

    @isTest
    public static void syncParticipantWithERPTest() {

        Restaurant__c restaurant = new Restaurant__c(
            Name = 'Test Restaurant',
            AverageMealCost__c = 0,
            CommissionRate__c = 10
        );
        Insert restaurant;

        Training_Course__c trainingCourse = new Training_Course__c(Name = 'Test Training Course');

		Insert trainingCourse;

        Contact trainerContact = new Contact(
            FirstName = 'John',
            LastName = 'Doe', 
            Email ='jdoe@test.net');
        Insert trainerContact;

        Training__c training = new Training__c(
            Name = 'Test Training',
            Restaurant__c = restaurant.id,
			Start_Date__c = Date.Today(),
			End_Date__c = Date.Today().addDays(2),
            Training_Course__c = trainingCourse.id,
			Trainer_Contact__c = trainerContact.id,
            Number_of_Participants__c = 0,
            Maximum_Participant_Capacity__c = 3
        );

        Insert training;

        Contact con = new Contact(FirstName = 'success', LastName = 'Carney', Email = 'dtcarney08@gmail.com');

        insert con;

        Participant__c participant = new Participant__c(Training__c = training.id, Contact_Name__c = con.id, ErpId__c = '1');

        Insert participant;
        participant = [
            SELECT Id, Contact_Name__r.Email,Contact_Name__r.Name, Training__r.Name, Status__c, ErpId__c
            FROM Participant__c 
            WHERE Id =: participant.Id
        ];


        Test.setMock(HttpCalloutMock.class, new MockERPResponseGenerator());
        RegistrationConfirmationQueueable.bypassPaymentLinkCallout = TRUE;
        Test.startTest();
        ERPparticipantCallout.syncParticipantWithERP(participant);
        System.debug('participant debug after callout: ' + participant);
        Test.stopTest();

    }



}