force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>A specific training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>The date and time that the training concluded</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Number_of_Participants__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Participants__c</fullName>
    <inlineHelpText>The number of people who participated in Training.</inlineHelpText>
    <label>Number of Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Restaurant__c.field-meta.xml
<CustomField>
    <fullName>Restaurant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If training takes too long, the restaurant will be included</inlineHelpText>
    <label>Restaurant</label>
    <referenceTo>Restaurant__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>The date and time that the training began</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Trainer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The trainer that will perform the training.</inlineHelpText>
    <label>Trainer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Training_Course__c.field-meta.xml
<CustomField>
    <fullName>Training_Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The course that was delivered in the training</inlineHelpText>
    <label>Training Course</label>
    <referenceTo>Training_Course__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TrainingRestServiceTest.cls
@isTest
public with sharing class TrainingRestServiceTest {

    @isTest
    public static void getTrainingSuccess(){

		Training_Course__c trainingCourse = new Training_Course__c(Name = 'Test Training Course');
		Insert trainingCourse;

        Account trainerAccount = new Account(Name = 'Trainer Account');
		Insert trainerAccount;

		Contact trainerContact = new Contact(FirstName = 'John',LastName = 'Doe',AccountId = trainerAccount.id);
        Insert trainerContact;
		
		Restaurant__c restaurant = new Restaurant__c(
            Name = 'Test Restaurant',
            AverageMealCost__c = 25,
            CommissionRate__c = 10
        );

        Insert restaurant;

        Training__c training = new Training__c(
            Name = 'Test Training',
            Restaurant__c = restaurant.Id,
			Start_Date__c = Date.Today(),
			End_Date__c = Date.Today().addDays(2),
            Number_of_Participants__c = 5,
			Training_Course__c = trainingCourse.id,
			Trainer_Contact__c = trainerContact.id
        );

        insert training;
        String trainingId = training.Id;

        RestRequest req = new RestRequest();
        req.addParameter('salesforceId', trainingId);
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/Trainings';
        req.httpMethod = 'GET';

        RestContext.request = req;
        RestContext.response= res;

        Test.startTest();
        TrainingRestService.getTraining();
        Test.stopTest();
        System.debug(res);
        Assert.areEqual(200, res.statusCode,'Response should be 200');


    }

    @isTest
    public static void getTrainingErrorTrainingNotFound(){

		Training_Course__c trainingCourse = new Training_Course__c(Name = 'Test Training Course');
		Insert trainingCourse;

        Account trainerAccount = new Account(Name = 'Trainer Account');
		Insert trainerAccount;

		Contact trainerContact = new Contact(FirstName = 'John',LastName = 'Doe',AccountId = trainerAccount.id);
        Insert trainerContact;
		
		Restaurant__c restaurant = new Restaurant__c(
            Name = 'Test Restaurant',
            AverageMealCost__c = 25,
            CommissionRate__c = 10
        );

        Insert restaurant;

        Training__c training = new Training__c(
            Name = 'Test Training',
            Restaurant__c = restaurant.Id,
			Start_Date__c = Date.Today(),
			End_Date__c = Date.Today().addDays(2),
            Number_of_Participants__c = 5,
			Training_Course__c = trainingCourse.id,
			Trainer_Contact__c = trainerContact.id
        );

        insert training;
        Training__c insertedTraining = [SELECT Id FROM Training__c LIMIT 1];
        String trainingId = insertedTraining.Id;
        delete training;

        RestRequest req = new RestRequest();
        req.addParameter('salesforceId', trainingId);
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/Trainings';
        req.httpMethod = 'GET';

        RestContext.request = req;
        RestContext.response= res;

        Test.startTest();
        TrainingRestService.getTraining();
        Test.stopTest();
        System.debug(res);
        Assert.areEqual(500, res.statusCode,'Response should be 500');

    }

    @isTest
    public static void getTrainingErrorMissingSalesforceId(){

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/Trainings';
        req.httpMethod = 'GET';

        RestContext.request = req;
        RestContext.response= res;

        Test.startTest();
        TrainingRestService.getTraining();
        Test.stopTest();
        System.debug(res);
        Assert.areEqual(400, res.statusCode,'Response should be 400');
    }

    @isTest
    public static void insertTrainings(){

		Training_Course__c trainingCourse = new Training_Course__c(Name = 'Test Training Course');
		Insert trainingCourse;

        Account trainerAccount = new Account(Name = 'Trainer Account');
		Insert trainerAccount;

		Contact trainerContact = new Contact(FirstName = 'John',LastName = 'Doe',AccountId = trainerAccount.id);
        Insert trainerContact;
		
		Restaurant__c restaurant = new Restaurant__c(
            Name = 'Test Restaurant',
            AverageMealCost__c = 25,
            CommissionRate__c = 10
        );

        Insert restaurant;

        DateTime startDateTime = DateTime.now();
        String startDate = startDateTime.format('yyyy-MM-dd HH:mm:ss');
        DateTime endDateTime = DateTime.now();
        String endDate = startDateTime.format('yyyy-MM-dd HH:mm:ss');


        RestRequest req = new RestRequest();
        req.addParameter('trainingName', 'TestTraining');
        req.addParameter('trainerId', trainerContact.Id);
        req.addParameter('courseId', trainingCourse.Id);
        req.addParameter('restaurantId', restaurant.Id);
        req.addParameter('startDate', startDate);
        req.addParameter('endDate', endDate);

        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/Trainings';
        req.httpMethod = 'POST';

        System.debug('Request: '+ req);
        RestContext.request = req;
        RestContext.response= res;

        Test.startTest();
        TrainingRestService.insertTraining();
        Test.stopTest();
        System.debug(res);
        Training__c insertedTraining = [SELECT Name, Start_Date__c, End_Date__c, Trainer_Contact__c, Restaurant__c, Training_Course__c FROM Training__c LIMIT 1];
        System.Assert.areEqual(Date.today(), insertedTraining.Start_Date__c);


    }








}