force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>A specific training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>The date and time that the training concluded</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Number_of_Participants__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Participants__c</fullName>
    <inlineHelpText>The number of people who participated in Training.</inlineHelpText>
    <label>Number of Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>The date and time that the training began</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Indicates whether a training is planned, happening now, or has concluded</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Trainer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The trainer that will perform the training.</inlineHelpText>
    <label>Trainer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TrainingReminderScheduled.cls
public with sharing class TrainingReminderScheduled implements Schedulable {
    public void execute(SchedulableContext sc){

        List<Training__c> trainings = [
            SELECT Id, Name, Start_Date__c, End_Date__c,
            Trainer_Contact__c, Trainer_Contact__r.FirstName, Number_of_Participants__c
            FROM Training__c
            WHERE Start_Date__c >= :Date.today().addDays(3) AND Start_Date__c < :Date.today().addDays(4)
        ];
        System.debug('trainings found: '+ trainings);

        List<Participant__c> activeParticipants = [
            SELECT Id, Name, Contact_Name__c,Contact_Name__r.Email, Training__c, Training__r.Name,
            Training__r.Start_Date__c, Training__r.End_Date__c
            FROM Participant__c
            WHERE Status__c = :TrainingService.ACTIVE_STATUS and Contact_Name__r.Email != null
            AND Training__c in :trainings
        ];
        System.debug('participants found: '+ activeParticipants);
        

        EmailService.notifyTrainerAboutTrainingStart(trainings);

        EmailService.notifyParticipantsAboutTrainingStart(activeParticipants);


    }



    public static List<Participant__c> participantsInTraining(Training__c training){
        List<Participant__c> participants = [
            SELECT Contact_Name__c,Contact_Name__r.Name
            FROM Participant__c
            WHERE Training__c = :training.Id AND Status__c = :TrainingService.ACTIVE_STATUS
        ];
        return participants;
    }



}