force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>A specific training event</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>The date and time that the training concluded</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Number_of_Participants__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Participants__c</fullName>
    <inlineHelpText>The number of people who participated in Training.</inlineHelpText>
    <label>Number of Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Restaurant__c.field-meta.xml
<CustomField>
    <fullName>Restaurant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If training takes too long, the restaurant will be included</inlineHelpText>
    <label>Restaurant</label>
    <referenceTo>Restaurant__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>The date and time that the training began</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Trainer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The trainer that will perform the training.</inlineHelpText>
    <label>Trainer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Training_Course__c.field-meta.xml
<CustomField>
    <fullName>Training_Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The course that was delivered in the training</inlineHelpText>
    <label>Training Course</label>
    <referenceTo>Training_Course__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TrainingFeedbackControllerTest.cls
@isTest
public with sharing class TrainingFeedbackControllerTest {
    @isTest
    public static void testSave(){

        Training_Course__c trainingCourse = new Training_Course__c(Name = 'Test Training Course');
		Insert trainingCourse;

        Account trainerAccount = new Account(Name = 'Trainer Account');
		Insert trainerAccount;

		Contact trainerContact = new Contact(FirstName = 'John',LastName = 'Doe',AccountId = trainerAccount.id);
        Insert trainerContact;
		
		Restaurant__c restaurant = new Restaurant__c(
            Name = 'Test Restaurant',
            AverageMealCost__c = 25,
            CommissionRate__c = 10
        );

        Insert restaurant;

        Training__c training = new Training__c(
            Name = 'Test Training',
            Restaurant__c = restaurant.Id,
			Start_Date__c = Date.Today(),
			End_Date__c = Date.Today().addDays(2),
            Number_of_Participants__c = 5,
			Training_Course__c = trainingCourse.id,
			Trainer_Contact__c = trainerContact.id
        );

        Test.setCurrentPage(Page.trainingfeedback);
        ApexPages.currentPage().getParameters().put('id', training.id);
        
        Test.startTest();
        TrainingFeedbackController controller = new TrainingFeedbackController();
        Test.stopTest();
        Assert.areEqual(training.Id, controller.feedback.Training__c);

    }

    @isTest
    public static void testFeedback(){

        Training_Course__c trainingCourse = new Training_Course__c(Name = 'Test Training Course');
		Insert trainingCourse;

        Account trainerAccount = new Account(Name = 'Trainer Account');
		Insert trainerAccount;

		Contact trainerContact = new Contact(FirstName = 'John',LastName = 'Doe',AccountId = trainerAccount.id);
        Insert trainerContact;
		
		Restaurant__c restaurant = new Restaurant__c(
            Name = 'Test Restaurant',
            AverageMealCost__c = 25,
            CommissionRate__c = 10
        );

        Insert restaurant;

        Training__c training = new Training__c(
            Name = 'Test Training',
            Restaurant__c = restaurant.Id,
			Start_Date__c = Date.Today(),
			End_Date__c = Date.Today().addDays(2),
            Number_of_Participants__c = 5,
			Training_Course__c = trainingCourse.id,
			Trainer_Contact__c = trainerContact.id
        );
        
        Test.setCurrentPage(Page.trainingfeedback);
        ApexPages.currentPage().getParameters().put('id', training.id);
        
        
        TrainingFeedbackController controller = new TrainingFeedbackController();

        Test.startTest();
        controller.save();
        Test.stopTest();
        List<Feedback__c> feedbacks = [SELECT Id, Training__c FROM Feedback__c];
        Assert.areEqual(1, feedbacks.size());
        Assert.areEqual(training.Id, feedbacks[0].Training__c);

    }

}    